name = "sunbox-theme-hugo"
license = "GPLv2"
licenselink = "https://github.com/eiyeron/sunbox-theme-hugo/blob/master/LICENSE.md"
description = "A gruvbox minimalistic theme"
homepage = "https://github.com/bake/solar-theme-hugo"
tags = ["blog", "dark", "responsive", "gruvbox"]
features = []
min_version = "0.0.1"

[author]
	name = "Eiyeron"
	homepage = "https://retroactive.me/"

[original]
	author = "bake"
	name = "solar-theme-hugo"
	repo = "https://github.com/bake/solar-theme-hugo"
